title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty

exclude:
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor

markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

collections:
  features:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "docs"
    values:
      layout: docs
  - scope:
      path: ""
      type: features
    values:
      layout: pages

plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

branch: master
