title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty

exclude:
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor

markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

collections:
  aplikasis:
    output: true
    permalink: /aplikasi/:name/

defaults:
  - scope:
      path: "docs"
    values:
      layout: docs
  - scope:
      path: ""
      type: aplikasis
    values:
      layout: aplikasi

plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

branch: master
