title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty
twitter_username: kelaspajakwith1
instagram: kelaspajakwith

encoding: UTF-8

exclude:
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor

markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules

collections:
  fiturs:
    output: true
    permalink: /fitur/:path/
  aspekpajaks:
    output: true
    permalink: /aspekpajak/:path/
defaults:
  - scope:
      path: ""
      type: fiturs
    values:
      layout: pages
  - scope:
      path: ""
      type: aspekpajaks
    values:
      layout: pages

plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
branch: master

# Google Analytics
google_analytics: UA-146778045-2

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration